<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.quartz.QuartzSupportTests" tests="15" skipped="8" failures="0" errors="0" timestamp="2021-04-16T01:52:25" hostname="DESKTOP-3R4DVF7" time="0.726">
  <properties/>
  <testcase name="jobDetailWithRunnableInsteadOfJob" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.003"/>
  <testcase name="schedulerRepositoryExposure" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.049"/>
  <testcase name="schedulerWithHsqlDataSource" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.612"/>
  <testcase name="schedulerWithQuartzJobBean" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="multipleSchedulers" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.008"/>
  <testcase name="schedulerAutoStartupFalse" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.01"/>
  <testcase name="schedulerWithSpringBeanJobFactoryAndJobSchedulingData" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerAccessorBean" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactory" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerAutoStartsOnContextRefreshedEventByDefault" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.002"/>
  <testcase name="schedulerWithTaskExecutor" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactoryAndQuartzJobBean" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerFactoryBeanWithApplicationContext" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.04"/>
  <testcase name="twoAnonymousMethodInvokingJobDetailFactoryBeans" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="schedulerWithSpringBeanJobFactoryAndParamMismatchNotIgnored" classname="org.springframework.scheduling.quartz.QuartzSupportTests" time="0.0">
    <skipped/>
  </testcase>
  <system-out><![CDATA[09:52:25.714 [scheduler_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger - An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Couldn't acquire next trigger: user lacks privilege or object not found: SCHED_TIME in statement [INSERT INTO QRTZ_FIRED_TRIGGERS (SCHED_NAME, ENTRY_ID, TRIGGER_NAME, TRIGGER_GROUP, INSTANCE_NAME, FIRED_TIME, SCHED_TIME, STATE, JOB_NAME, JOB_GROUP, IS_NONCONCURRENT, REQUESTS_RECOVERY, PRIORITY) VALUES('scheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2910) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3849) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.0.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) [quartz-2.3.0.jar:?]
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: SCHED_TIME in statement [INSERT INTO QRTZ_FIRED_TRIGGERS (SCHED_NAME, ENTRY_ID, TRIGGER_NAME, TRIGGER_GROUP, INSTANCE_NAME, FIRED_TIME, SCHED_TIME, STATE, JOB_NAME, JOB_GROUP, IS_NONCONCURRENT, REQUESTS_RECOVERY, PRIORITY) VALUES('scheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[quartz-2.3.0.jar:?]
	at com.sun.proxy.$Proxy76.prepareStatement(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertFiredTrigger(StdJDBCDelegate.java:2645) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2893) ~[quartz-2.3.0.jar:?]
	... 5 more
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: SCHED_TIME
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.ParserDQL.readSimpleColumnName(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.ParserDQL.readSimpleColumnNames(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.ParserDML.compileInsertStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.ParserCommand.compilePart(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Session.compileStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.StatementManager.compile(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.4.1.jar:2.4.1]
	at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[quartz-2.3.0.jar:?]
	at com.sun.proxy.$Proxy76.prepareStatement(Unknown Source) ~[?:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertFiredTrigger(StdJDBCDelegate.java:2645) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2893) ~[quartz-2.3.0.jar:?]
	... 5 more
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
